config/routes.rb
Socialsight::Application.routes.draw do
  get "comment/index"

  get "page/index"

  resources :posts
  resources :pages
  resources :comments

  get "home/index"

  root :to => "home#index"

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  validates :author, :presence => true
  validates :text, :presence => true,
		 :length => { :minimum => 10 }

  belongs_to :post

  

end

app/models/page.rb
class Page < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
	validates :title, :presence => true
	validates :author, :presence => true
	validates :text, :presence => true,
			 :length => { :minimum => 20 }
	# validates :time, :presence => true -- can just use created_at
	# add has many comments
	has_many :comments

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comment_controller.rb
class CommentController < ApplicationController
  def index
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
	@posts = Post.all
	@pages = Page.all
  end

end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def index
	@pages = Page.all

	respond_to do |format|
        format.html # index.html.erb
        format.xml  { render :xml => @pages }
  end

  def show
	@pages = Page.find(params[:id])


  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.xml
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.xml
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.xml
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.xml
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to(@post, :notice => 'Post was successfully created.') }
        format.xml  { render :xml => @post, :status => :created, :location => @post }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.xml
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to(@post, :notice => 'Post was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.xml
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to(posts_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comment/index.html.erb
<h1>Comment#index</h1>
<p>Find me in app/views/comment/index.html.erb</p>

app/views/home/index.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<!--

Design by Free CSS Templates
http://www.freecsstemplates.org
Released for free under a Creative Commons Attribution 2.5 License

Title      : Emporium
Version    : 1.0
Released   : 20090222
Description: A two-column, fixed-width and lightweight template ideal for 1024x768 resolutions. Suitable for blogs and small websites.

-->
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title>Mobile Wingman</title>
<meta name="keywords" content="" />
<meta name="description" content="" />
<link href="stylesheets/default.css" rel="stylesheet" type="text/css" />


</head>
<body>

<div id="wrapper">
<!-- start header -->
<div id="logo">
	<!--<h1><a href="#">MobileWingman </a></h1>-->
	<h1><a href="#"><img src="/images/logo3.png" style="margin:-10px 0px -10px 0px; padding=0;" /></a></h1>
	<h2> &raquo;&nbsp;&nbsp;&nbsp;A mobile solution for contact management</h2>
</div>
<div id="header">
	
	<div id="menu">
		<ul>
			<li class="current_page_item"><%= link_to 'home', '' %></li>
			<li><%= link_to 'overview', '/overview.html' %></li>
			<li><%= link_to 'media', '/media.html' %></li>
			<li><%= link_to 'blog', '/posts' %></li>
			<li><%= link_to 'about us', '/aboutus.html' %></li>
		</ul>
	</div>
</div>
<!-- end header -->
</div>
<!-- start page -->
<div id="page">
	<!-- start content -->
	<div id="content">
		<div class="post">
			<h1 class="title">Meet MobileWingman </h1>
			<div class="entry">
				<p>An application that uses mobile technology to give you information about your surroundings.  MobileWingman uses your
				mobile device's camera to detect people in real-time and then augments reality with up to date information about
				them. </p>

			<!--<div>
				<img src="images/logo2.png" />
			</div>-->

				<p>If you tag a contact with MobileWingman, it can add information from their twitter and facebook accounts to your 					mobile screen whenever they walk into the application's view.  While this may seem trivial, there are a lot of applications for this technology that allow you to quickly catch up with contacts you haven't seen in a while.<p>
				<h22>Such as:</h22>
				<ul>
					<li>Relationship Status</li>
					<li>Home Town</li>
					<li>Networks</li>
					<li>Likes</li>
					<li>Hobbies</li>
					<li>Current Status</li>
					<li>Most Recent Tweet</li>
					<li>Favorite Music</li>
				</ul>
			</div>
			<!--<div class="meta">
				<p class="links"><a href="#" class="more">Read full article</a> <b>|</b> <a href="#" class="comments">Comments (32)</a></p>
			</div>-->
		</div>


		<div style="text-align:center; font-size:50px; height:55px">
			Check out our demo video!
		</div>
		<div style="text-align:center; height:250px">
			<iframe src="http://player.vimeo.com/video/1072082" width="400" height="225" frameborder="0">
			</iframe>
			<p>
		</div>

		<!--<div class="post">
			<h2 class="title">Lorem Ipsum Dolor Volutpat</h2>
			<div class="entry">
				<p>Curabitur tellus. Phasellus tellus turpis, iaculis in, faucibus lobortis, posuere in, lorem. Donec a ante. Donec neque purus, adipiscing id, eleifend a, cursus vel, odio. Vivamus varius justo sit amet leo. Morbi sed libero. Vestibulum blandit augue at mi. Praesent fermentum lectus eget diam. Nam cursus, orci sit amet porttitor iaculis, ipsum massa aliquet nulla, non elementum mi elit a mauris. In hac habitasse platea.</p>
				<p>Vestibulum blandit augue at mi. Praesent fermentum lectus eget diam. Nam cursus, orci sit amet porttitor iaculis, ipsum massa aliquet nulla, non elementum mi elit a mauris. </p>
			</div>
			<div class="meta">
				<p class="links"><a href="#" class="more">Read full article</a> <b>|</b> <a href="#" class="comments">Comments (32)</a></p>
			</div>
		</div>-->
	</div>
	<!-- end content -->
	<!-- start sidebar -->
	<div id="sidebar">
		<ul>
			<!--<li id="search">
				<h2>Search</h2>
				<form method="get" action="">
					<fieldset>
					<input type="text" id="s" name="s" value="" />
					<input type="submit" id="x" value="Search" />
					</fieldset>
				</form>
			</li>-->
			<li>
				<h2>Recent Blog Posts</h2>
				<ul>
				     <% for i in 0..6 #try and post 7 posts%>
					<% if not @posts[i].nil? %>
					    <li>
						<%= link_to (@posts[i].title.to_s + " (by " + @posts[i].author + ")"), @posts[i] %>
					    </li>
					<% end %>
  				     <% end # loop of posts %>
					<!--<li><a href="#">Fusce dui neque fringilla</a></li>
					<li><a href="#">Eget tempor eget nonummy</a></li>
					<li><a href="#">Magna lacus bibendum mauris</a></li>
					<li><a href="#">Nec metus sed donec</a></li>
					<li><a href="#">Magna lacus bibendum mauris</a></li>
					<li><a href="#">Velit semper nisi molestie</a></li>
					<li><a href="#">Eget tempor eget nonummy</a></li>-->
				</ul>
			</li>
			<!--<li>
				<h2>Volutpat Dolore</h2>
				<ul>
					<li><a href="#">Nec metus sed donec</a></li>
					<li><a href="#">Magna lacus bibendum mauris</a></li>
					<li><a href="#">Velit semper nisi molestie</a></li>
					<li><a href="#">Eget tempor eget nonummy</a></li>
					<li><a href="#">Nec metus sed donec</a></li>
					<li><a href="#">Magna lacus bibendum mauris</a></li>
					<li><a href="#">Velit semper nisi molestie</a></li>
				</ul>
			</li>-->
		</ul>
	</div>
	<!-- end sidebar -->
	<div style="clear: both;">&nbsp;</div>
</div>
<!-- end page -->
<!-- start footer -->
<div id="footer">
	<p id="legal">( c ) 2008. All Rights Reserved. <a href="http://www.freecsstemplates.org/">Bestfriends</a> designed by <a href="http://www.freecsstemplates.org/">Free CSS Templates</a>.</p>
</div>
<!-- end footer -->
</body>
</html>

app/views/home/overview.html.erb
<p>OverView works!</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Socialsight</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/overview.html.erb
<p>OverView works!</p>

app/views/page/index.html.erb
<h1>Page#index</h1>
<p>Find me in app/views/page/index.html.erb</p>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :text %><br />
    <%= f.text_area :text %>
  </div>
  <div class="field">
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :time %><br />
    <%= f.date_select :time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<!--

Design by Free CSS Templates
http://www.freecsstemplates.org
Released for free under a Creative Commons Attribution 2.5 License

Title      : Emporium
Version    : 1.0
Released   : 20090222
Description: A two-column, fixed-width and lightweight template ideal for 1024x768 resolutions. Suitable for blogs and small websites.

-->
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title>Mobile Wingman</title>
<meta name="keywords" content="" />
<meta name="description" content="" />
<link href="stylesheets/default2.css" rel="stylesheet" type="text/css" />


</head>
<body>

<div id="wrapper">
<!-- start header -->
<div id="logo">
	<!--<h1><a href="#">MobileWingman </a></h1>-->
	<h1><a href="#"><img src="images/logo3.png" style="margin:-10px 0px -10px 0px; padding=0;" /></a></h1>
	<h2> &raquo;&nbsp;&nbsp;&nbsp;A mobile solution for contact management</h2>
</div>
<div id="header">
	
	<div id="menu">
		<ul>
			<li class="current_page_item"><%= link_to 'home', '' %></li>
			<li><%= link_to 'overview', '/overview.html' %></li>
			<li><%= link_to 'media', '/media.html' %></li>
			<li><%= link_to 'blog', '/posts' %></li>
			<li><%= link_to 'about us', '/aboutus.html' %></li>
		</ul>
	</div>
</div>
<!-- end header -->
</div>
<!-- start page -->
<div id="page">
	<!-- start content -->
	<div id="content">
		<div class="post">
			<h1 class="title">The Blog </h1>
			

			<% (@posts.length - 1).downto(0) do |i| %>
			<div>   
			 <div>
				<h12> <%= @posts[i].title %> </h12></br>
				<h13> <%= "By " + @posts[i].author %> </h13>
				<p> <%= @posts[i].text %> </p>
				
			    </div>
				<h11>COMMENTS:</h11>
				<ul>
					<% @posts[i].comments.each do |com| %>
						<li><%= com.text + " --by " + com.author %></li>
					<% end %>
				</ul>
				<h11> <%= link_to "Add Comment", new_comment_path %></h11>
			    </div>
			<% end %>


			<div>
				<%= link_to 'New Post', new_post_path %>
			</div>			

			<!--<div class="meta">
				<p class="links"><a href="#" class="more">Read full article</a> <b>|</b> <a href="#" class="comments">Comments (32)</a></p>
			</div>-->
		</div>

		<!--<div class="post">
			<h2 class="title">Lorem Ipsum Dolor Volutpat</h2>
			<div class="entry">
				<p>Curabitur tellus. Phasellus tellus turpis, iaculis in, faucibus lobortis, posuere in, lorem. Donec a ante. Donec neque purus, adipiscing id, eleifend a, cursus vel, odio. Vivamus varius justo sit amet leo. Morbi sed libero. Vestibulum blandit augue at mi. Praesent fermentum lectus eget diam. Nam cursus, orci sit amet porttitor iaculis, ipsum massa aliquet nulla, non elementum mi elit a mauris. In hac habitasse platea.</p>
				<p>Vestibulum blandit augue at mi. Praesent fermentum lectus eget diam. Nam cursus, orci sit amet porttitor iaculis, ipsum massa aliquet nulla, non elementum mi elit a mauris. </p>
			</div>
			<div class="meta">
				<p class="links"><a href="#" class="more">Read full article</a> <b>|</b> <a href="#" class="comments">Comments (32)</a></p>
			</div>
		</div>-->
	</div>
	<!-- end content -->
	<!-- start sidebar -->
	<div id="sidebar">
		<ul>
			<!--<li id="search">
				<h2>Search</h2>
				<form method="get" action="">
					<fieldset>
					<input type="text" id="s" name="s" value="" />
					<input type="submit" id="x" value="Search" />
					</fieldset>
				</form>
			</li>-->
			<li>
				<h2>Recent Blog Posts</h2>
				<ul>
				     <% for i in 0..6 #try and post 7 posts%>
					<% if not @posts[i].nil? %>
					    <li>
						<%= link_to (@posts[i].title.to_s + " (by " + @posts[i].author + ")"), @posts[i] %>
					    </li>
					<% end %>
  				     <% end # loop of posts %>
					<!--<li><a href="#">Fusce dui neque fringilla</a></li>
					<li><a href="#">Eget tempor eget nonummy</a></li>
					<li><a href="#">Magna lacus bibendum mauris</a></li>
					<li><a href="#">Nec metus sed donec</a></li>
					<li><a href="#">Magna lacus bibendum mauris</a></li>
					<li><a href="#">Velit semper nisi molestie</a></li>
					<li><a href="#">Eget tempor eget nonummy</a></li>-->
				</ul>
			</li>
			<!--<li>
				<h2>Volutpat Dolore</h2>
				<ul>
					<li><a href="#">Nec metus sed donec</a></li>
					<li><a href="#">Magna lacus bibendum mauris</a></li>
					<li><a href="#">Velit semper nisi molestie</a></li>
					<li><a href="#">Eget tempor eget nonummy</a></li>
					<li><a href="#">Nec metus sed donec</a></li>
					<li><a href="#">Magna lacus bibendum mauris</a></li>
					<li><a href="#">Velit semper nisi molestie</a></li>
				</ul>
			</li>-->
		</ul>
	</div>
	<!-- end sidebar -->
	<div style="clear: both;">&nbsp;</div>
</div>
<!-- end page -->
<!-- start footer -->
<div id="footer">
	<p id="legal">( c ) 2008. All Rights Reserved. <a href="http://www.freecsstemplates.org/">Bestfriends</a> designed by <a href="http://www.freecsstemplates.org/">Free CSS Templates</a>.</p>
</div>
<!-- end footer -->
</body>
</html>

app/views/posts/new.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<!--

Design by Free CSS Templates
http://www.freecsstemplates.org
Released for free under a Creative Commons Attribution 2.5 License

Title      : Emporium
Version    : 1.0
Released   : 20090222
Description: A two-column, fixed-width and lightweight template ideal for 1024x768 resolutions. Suitable for blogs and small websites.

-->
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title>Mobile Wingman</title>
<meta name="keywords" content="" />
<meta name="description" content="" />
<link href="stylesheets/default2.css" rel="stylesheet" type="text/css" />


</head>
<body>

<div id="wrapper">
<!-- start header -->
<div id="logo">
	<!--<h1><a href="#">MobileWingman </a></h1>-->
	<h1><a href="#"><img src="../images/logo3.png" style="margin:-10px 0px -10px 0px; padding=0;" /></a></h1>
	<h2> &raquo;&nbsp;&nbsp;&nbsp;A mobile solution for contact management</h2>
</div>
<div id="header">
	
	<div id="menu">
		<ul>
			<li class="current_page_item"><%= link_to 'home', '' %></li>
			<li><%= link_to 'overview', '/overview.html' %></li>
			<li><%= link_to 'media', '/media.html' %></li>
			<li><%= link_to 'blog', '/posts' %></li>
			<li><%= link_to 'about us', '/aboutus.html' %></li>
		</ul>
	</div>
</div>
<!-- end header -->
</div>
<!-- start page -->
<div id="page">
	<!-- start content -->
	<div id="content">
		<div class="post">
			<h1 class="title">New Blog Post </h1>
			<div class="entry">
			

				<%= render 'form' %>

				<%= link_to 'Back', posts_path %>

	
			</div>
			<!--<div class="meta">
				<p class="links"><a href="#" class="more">Read full article</a> <b>|</b> <a href="#" class="comments">Comments (32)</a></p>
			</div>-->
		</div>

		<!--<div class="post">
			<h2 class="title">Lorem Ipsum Dolor Volutpat</h2>
			<div class="entry">
				<p>Curabitur tellus. Phasellus tellus turpis, iaculis in, faucibus lobortis, posuere in, lorem. Donec a ante. Donec neque purus, adipiscing id, eleifend a, cursus vel, odio. Vivamus varius justo sit amet leo. Morbi sed libero. Vestibulum blandit augue at mi. Praesent fermentum lectus eget diam. Nam cursus, orci sit amet porttitor iaculis, ipsum massa aliquet nulla, non elementum mi elit a mauris. In hac habitasse platea.</p>
				<p>Vestibulum blandit augue at mi. Praesent fermentum lectus eget diam. Nam cursus, orci sit amet porttitor iaculis, ipsum massa aliquet nulla, non elementum mi elit a mauris. </p>
			</div>
			<div class="meta">
				<p class="links"><a href="#" class="more">Read full article</a> <b>|</b> <a href="#" class="comments">Comments (32)</a></p>
			</div>
		</div>-->
	</div>
	<!-- end content -->
	<!-- start sidebar -->
	<div id="sidebar">
		<ul>
			<!--<li id="search">
				<h2>Search</h2>
				<form method="get" action="">
					<fieldset>
					<input type="text" id="s" name="s" value="" />
					<input type="submit" id="x" value="Search" />
					</fieldset>
				</form>
			</li>-->
			<li>
				<h2>Contact Us!</h2>
				<ul>
					<h12>mobilewingman@gmail.com</h12>
					<!--<li><a href="#">Fusce dui neque fringilla</a></li>
					<li><a href="#">Eget tempor eget nonummy</a></li>
					<li><a href="#">Magna lacus bibendum mauris</a></li>
					<li><a href="#">Nec metus sed donec</a></li>
					<li><a href="#">Magna lacus bibendum mauris</a></li>
					<li><a href="#">Velit semper nisi molestie</a></li>
					<li><a href="#">Eget tempor eget nonummy</a></li>-->
				</ul>
			</li>
			<!--<li>
				<h2>Volutpat Dolore</h2>
				<ul>
					<li><a href="#">Nec metus sed donec</a></li>
					<li><a href="#">Magna lacus bibendum mauris</a></li>
					<li><a href="#">Velit semper nisi molestie</a></li>
					<li><a href="#">Eget tempor eget nonummy</a></li>
					<li><a href="#">Nec metus sed donec</a></li>
					<li><a href="#">Magna lacus bibendum mauris</a></li>
					<li><a href="#">Velit semper nisi molestie</a></li>
				</ul>
			</li>-->
		</ul>
	</div>
	<!-- end sidebar -->
	<div style="clear: both;">&nbsp;</div>
</div>
<!-- end page -->
<!-- start footer -->
<div id="footer">
	<p id="legal">( c ) 2008. All Rights Reserved. <a href="http://www.freecsstemplates.org/">Bestfriends</a> designed by <a href="http://www.freecsstemplates.org/">Free CSS Templates</a>.</p>
</div>
<!-- end footer -->
</body>
</html>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @post.title %>
</p>

<p>
  <b>Text:</b>
  <%= @post.text %>
</p>

<p>
  <b>Author:</b>
  <%= @post.author %>
</p>

<p>
  <b>Time:</b>
  <%= @post.time %>
</p>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>